### ISSUE TITLE
Standard requires Node v4

### ISSUE THREAD

**Issue by LoicVerrall** [UniNinja/mobile#18]
StandardJS is not enforced at the moment as the Travis environment is using < Node v4

**Comment by danarth** [comment]
Hi @LoicVerrall,

This is due to the limited nature of the `.travis.yml` file. From the [Travis CI docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions):

> The easiest way to specify Node.js versions is to use one or more of the latest releases in your `.travis.yml`:
>
> - `node` latest stable Node.js release
> - `iojs` latest stable io.js release
> - `lts/*` latest LTS Node.js release
> ```yml
> language: node_js
> node_js:
>  - "iojs"
>  - "7"
> ```

So if you have a specific version of Node you wish to use, then go for it, but on the server side we use:
```yml
node_js:
  - node
```
Which uses the latest stable release of Node! 🎉

**Comment by LoicVerrall** [comment]
Thanks for explaining that. I will close this issue now as it is resolved by #17.
